name: yomu

services:
  web:
    container_name: web
    image: agn907/yomu
    ports:
      - '3000:3000'
    env_file:
      - path: .env
        required: false
      - path: .env.local
        required: true
    volumes:
      - yomu-database:/app/database

volumes:
  yomu-database:
