name: yomu

services:
  web:
    container_name: web
    image: agn907/yomu
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: './database/yomu.db'
    volumes:
      - yomu-database:/app/database

volumes:
  yomu-database:
